// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };
"use client";

import React from "react";
import { usePathname } from "next/navigation";

import Tab from "../../components/Tab";

export default function RootLayout({ children }) {
	const pathname = usePathname();
	return (
		<div>
			{/* <div class="w-1/4 ml-16 my-6">
				<Tab selection={pathname.split("/").pop()} />
			</div> */}
			{children}
		</div>
	);
}
