// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };
"use client";

import React from "react";
import { usePathname } from "next/navigation";

import Tab from "../../components/Tab";

export default function RootLayout({ children }) {
	const pathname = usePathname();
	return (
		<div>
			<Tab selection={pathname.split("/").pop()} />
			{children}
		</div>
	);
}
